CREATE TABLE IF NOT EXISTS STUDENTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    SURNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(15),
    BRANCH VARCHAR(50),
    JOINING_YEAR VARCHAR(10)
    );
